export const COUNTRIES: [string, string][] = [
  ['Nhật Bản', 'manga'],
  ['Trung Quốc', 'manhua'],
  ['Hàn Quốc', 'manhwa'],
  ['Khác', 'other'],
];

export const SORTS: [string, string][] = [
  ['Không', ''],
  ['Mới nhất', 'latest'],
  ['Cũ nhất', 'oldest'],
  ['Đánh giá', 'rating'],
  ['A-Z', 'alphabet'],
  ['Mới cập nhật', 'recently_updated'],
  ['Xem nhiều nhất', 'mostView'],
];

export const CHAPTER_COUNTS: [string, string][] = [
  ['Không', ''],
  ['>= 1 chapters', '1'],
  ['>= 3 chapters', '3'],
  ['>= 5 chapters', '5'],
  ['>= 10 chapters', '10'],
  ['>= 20 chapters', '20'],
  ['>= 30 chapters', '30'],
  ['>= 50 chapters', '50'],
];

export const STATUSES: [string, string][] = [
  ['Hoàn thành', '1'],
  ['Đang tiến hành', '0'],
];

export const GENRES: [string, string][] = [
  ['Action', '1'],
  ['Adventure', '2'],
  ['Fantasy', '3'],
  ['Manhua', '4'],
  ['Chuyển Sinh', '5'],
  ['Truyện Màu', '6'],
  ['Xuyên Không', '7'],
  ['Manhwa', '8'],
  ['Drama', '9'],
  ['Historical', '10'],
  ['Manga', '11'],
  ['Seinen', '12'],
  ['Comedy', '13'],
  ['Martial Arts', '14'],
  ['Mystery', '15'],
  ['Romance', '16'],
  ['Shounen', '17'],
  ['Sports', '18'],
  ['Supernatural', '19'],
  ['Harem', '20'],
  ['Webtoon', '21'],
  ['School', '22'],
  ['Psychological', '23'],
  ['Cổ Đại', '24'],
  ['Ecchi', '25'],
  ['Gender Bender', '26'],
  ['Shoujo', '27'],
  ['Slice of Life', '28'],
  ['Ngôn Tình', '29'],
  ['Horror', '30'],
  ['Sci-fi', '31'],
  ['Tragedy', '32'],
  ['Mecha', '33'],
  ['Comic', '34'],
  ['One shot', '35'],
  ['Shoujo Ai', '36'],
  ['Anime', '37'],
  ['Josei', '38'],
  ['Smut', '39'],
  ['Shounen Ai', '40'],
  ['Mature', '41'],
  ['Soft Yuri', '42'],
  ['Adult', '43'],
  ['Doujinshi', '44'],
  ['Live action', '45'],
  ['Trinh Thám', '46'],
  ['Việt Nam', '47'],
  ['Truyện Scan', '48'],
  ['Cooking', '49'],
  ['Tạp chí truyện tranh', '50'],
  ['16+', '51'],
  ['Thiếu Nhi', '52'],
  ['Soft Yaoi', '53'],
  ['Đam Mỹ', '54'],
  ['BoyLove', '55'],
  ['Yaoi', '56'],
  ['18+', '57'],
  ['Người Thú', '58'],
  ['ABO', '59'],
  ['Mafia', '60'],
  ['Isekai', '61'],
  ['Hệ Thống', '62'],
  ['NTR', '63'],
  ['Yuri', '64'],
  ['Girl Love', '65'],
  ['Demons', '66'],
  ['Huyền Huyễn', '67'],
  ['Detective', '68'],
  ['Trọng Sinh', '69'],
  ['Magic', '70'],
  ['Military', '71'],
];
