export const GENRES: [string, string][] = [
  ['BDSM', 'bdsm'],
  ['Bebes', 'bebes'],
  ['Bestias', 'bestias'],
  ['BL Sin Censura', 'bl-sin-censura'],
  ['Boys Love', 'boys-love'],
  ['Che Tenete Un Poco De Amor Propio', 'che-tenete-un-poco-de-amor-propio'],
  ['Ciencia Ficción', 'ciencia-ficcion'],
  ['Comedia', 'comedia'],
  ['Crimen', 'crimen'],
  ['Del Campo', 'del-campo'],
  ['Demonios', 'demonios'],
  ['Deportes', 'deportes'],
  ['Drama', 'drama'],
  ['Escolar', 'escolar'],
  ['Espacial', 'espacial'],
  ['Fantasía', 'fantasia'],
  ['Furro', 'furro'],
  ['Harem', 'harem'],
  ['Harem Inverso', 'harem-inverso'],
  ['Historia', 'historia'],
  ['Josei', 'josei'],
  ['Juego', 'juego'],
  ['Mafia', 'mafia'],
  ['Magia', 'magia'],
  ['Manhwa +19', 'manhwa-19'],
  ['Militar', 'militar'],
  ['Moderno', 'moderno'],
  ['Morocho Hermoso', 'morocho-hermoso'],
  ['Mucho Gogogo', 'mucho-gogogo'],
  ['Música', 'musica'],
  ['Novela', 'novela'],
  ['Odio-Amor', 'odio-amor'],
  ['Omegaverse', 'omegaverse'],
  ['Psicológico', 'psicologico'],
  ['Reencarnación', 'reencarnacion'],
  ['Relación Por Convivencia', 'relacion-por-convivencia'],
  ['Romance', 'romance'],
  ['Smut', 'smut'],
  ['Telenovela', 'telenovela'],
  ['Tetón', 'teton'],
  ['Toxicidad', 'toxicidad'],
  ['Toxicidad Nivel Chernóbil', 'toxicidad-nivel-chernobil'],
  ['Universitario', 'universitario'],
  ['Venganza', 'venganza'],
  ['Shoujo', 'Shoujo'],
  ['Shounen', 'Shounen'],
  ['Seinen', 'Seinen'],
  ['+18 Sin Censura', '+ 18 Sin Censura'],
  ['NoBL💌', 'nobl'],
  ['Girls Love', 'gl'],
  ['Adulto', 'adulto'],
  ['+18', '18'],
  ['Sistema', 'sistema'],
  ['Acción', 'Acción'],
  ['Aventura', 'Aventura'],
  ['Sobrenatural', 'Sobrenatural'],
  ['Transmigración', 'Transmigración'],
  ['Misterio', 'misterio'],
  ['Tragedia', 'tragedia'],
  ['Horror', 'horror'],
  ['BL', 'bl'],
  ['Thriller', 'thriller'],
];
