import type { Filter } from '@matane/extension-sdk';

export const GENRES: [string, string][] = [
  ['Acción', '2'],
  ['Animación', '6198'],
  ['Apocalíptico', '861'],
  ['Artes Marciales', '26'],
  ['Aventura', '3'],
  ['Boys Love', '103'],
  ['Ciberpunk', '356'],
  ['Ciencia Ficción', '21'],
  ['Comedia', '4'],
  ['Crimen', '41'],
  ['Demonios', '88'],
  ['Deporte', '37'],
  ['Drama', '15'],
  ['Ecchi', '32'],
  ['Extranjero', '1168'],
  ['Familia', '1027'],
  ['Fantasia', '5'],
  ['Girls Love', '22'],
  ['Gore', '181'],
  ['Guerra', '1109'],
  ['Género Bender', '183'],
  ['Harem', '8'],
  ['Historia', '81'],
  ['Horror', '82'],
  ['Magia', '6'],
  ['Mecha', '144'],
  ['Militar', '342'],
  ['Misterio', '40'],
  ['Musica', '403'],
  ['Niños', '219'],
  ['Oeste', '141'],
  ['Parodia', '820'],
  ['Policiaco', '111'],
  ['Psicológico', '36'],
  ['Realidad', '147'],
  ['Realidad Virtual', '27'],
  ['Recuentos de la vida', '33'],
  ['Reencarnación', '60'],
  ['Romance', '16'],
  ['Samurái', '99'],
  ['Sobrenatural', '7'],
  ['Superpoderes', '116'],
  ['Supervivencia', '112'],
  ['Telenovela', '470'],
  ['Thriller', '49'],
  ['Tragedia', '46'],
  ['Traps', '1464'],
  ['Vampiros', '345'],
  ['Vida Escolar', '23'],
];

export const TYPES: [string, string][] = [
  ['Doujinshi', '207'],
  ['Manga', '14'],
  ['Manhua', '31'],
  ['Manhwa', '87'],
  ['Novela', '214'],
  ['OEL', '976'],
  ['One shot', '12312'],
];

export const STATUSES: [string, string][] = [
  ['Publicándose', '12'],
  ['Finalizado', '19'],
  ['Pausado', '174'],
  ['Cancelado', '198'],
];

export const GROUPS: Filter[] = [
  {
    type: 'group',
    id: 'genres',
    label: 'Géneros',
    filters: GENRES.map(([label, value]): Filter => ({ type: 'checkbox', id: `genres.${value}`, label })),
  },
  {
    type: 'group',
    id: 'type',
    label: 'Tipo',
    filters: TYPES.map(([label, value]): Filter => ({ type: 'checkbox', id: `type.${value}`, label })),
  },
  {
    type: 'group',
    id: 'status',
    label: 'Estado',
    filters: STATUSES.map(([label, value]): Filter => ({ type: 'checkbox', id: `status.${value}`, label })),
  },
];
