import type { Filter } from '@matane/extension-sdk';

export const GROUPS: Filter[] = [
  {
    type: 'group',
    id: 'gendersId',
    label: 'Géneros',
    filters: [
      { type: 'checkbox', id: 'gendersId.1', label: 'Accion' },
      { type: 'checkbox', id: 'gendersId.56', label: 'Adulto' },
      { type: 'checkbox', id: 'gendersId.3', label: 'Animación' },
      { type: 'checkbox', id: 'gendersId.4', label: 'Apocaliptico' },
      { type: 'checkbox', id: 'gendersId.23', label: 'Artes Marciales' },
      { type: 'checkbox', id: 'gendersId.2', label: 'Aventura' },
      { type: 'checkbox', id: 'gendersId.64', label: 'Bestias' },
      { type: 'checkbox', id: 'gendersId.5', label: 'Boys Love' },
      { type: 'checkbox', id: 'gendersId.61', label: 'Boys Love' },
      { type: 'checkbox', id: 'gendersId.8', label: 'Ciberpunk' },
      { type: 'checkbox', id: 'gendersId.36', label: 'Ciencia Ficción' },
      { type: 'checkbox', id: 'gendersId.6', label: 'Comedia' },
      { type: 'checkbox', id: 'gendersId.7', label: 'Crimen' },
      { type: 'checkbox', id: 'gendersId.9', label: 'Demonios' },
      { type: 'checkbox', id: 'gendersId.39', label: 'Deporte' },
      { type: 'checkbox', id: 'gendersId.63', label: 'Dragones' },
      { type: 'checkbox', id: 'gendersId.10', label: 'Drama' },
      { type: 'checkbox', id: 'gendersId.11', label: 'Ecchi' },
      { type: 'checkbox', id: 'gendersId.14', label: 'Extranjero' },
      { type: 'checkbox', id: 'gendersId.12', label: 'Familia' },
      { type: 'checkbox', id: 'gendersId.13', label: 'Fantasia' },
      { type: 'checkbox', id: 'gendersId.62', label: 'Fantasmas' },
      { type: 'checkbox', id: 'gendersId.15', label: 'Género Bender' },
      { type: 'checkbox', id: 'gendersId.16', label: 'Girls Love' },
      { type: 'checkbox', id: 'gendersId.17', label: 'Gore' },
      { type: 'checkbox', id: 'gendersId.47', label: 'Guerra' },
      { type: 'checkbox', id: 'gendersId.18', label: 'Harem' },
      { type: 'checkbox', id: 'gendersId.19', label: 'Historia' },
      { type: 'checkbox', id: 'gendersId.20', label: 'Horror' },
      { type: 'checkbox', id: 'gendersId.53', label: 'Isekai' },
      { type: 'checkbox', id: 'gendersId.22', label: 'Magia' },
      { type: 'checkbox', id: 'gendersId.49', label: 'Mazmorra' },
      { type: 'checkbox', id: 'gendersId.24', label: 'Mecha' },
      { type: 'checkbox', id: 'gendersId.25', label: 'Militar' },
      { type: 'checkbox', id: 'gendersId.26', label: 'Misterio' },
      { type: 'checkbox', id: 'gendersId.27', label: 'Musica' },
      { type: 'checkbox', id: 'gendersId.21', label: 'Niños' },
      { type: 'checkbox', id: 'gendersId.48', label: 'Oeste' },
      { type: 'checkbox', id: 'gendersId.28', label: 'Parodia' },
      { type: 'checkbox', id: 'gendersId.29', label: 'Policiaco' },
      { type: 'checkbox', id: 'gendersId.30', label: 'Psicológico' },
      { type: 'checkbox', id: 'gendersId.31', label: 'Realidad' },
      { type: 'checkbox', id: 'gendersId.46', label: 'Realidad Virtual' },
      { type: 'checkbox', id: 'gendersId.37', label: 'Recuentos de la vida' },
      { type: 'checkbox', id: 'gendersId.32', label: 'Reencarnación' },
      { type: 'checkbox', id: 'gendersId.52', label: 'Regresion' },
      { type: 'checkbox', id: 'gendersId.58', label: 'Regresión' },
      { type: 'checkbox', id: 'gendersId.33', label: 'Romance' },
      { type: 'checkbox', id: 'gendersId.34', label: 'Samurái' },
      { type: 'checkbox', id: 'gendersId.50', label: 'Sistemas' },
      { type: 'checkbox', id: 'gendersId.57', label: 'Smut' },
      { type: 'checkbox', id: 'gendersId.40', label: 'Supernatural' },
      { type: 'checkbox', id: 'gendersId.41', label: 'Superpoderes' },
      { type: 'checkbox', id: 'gendersId.42', label: 'Supervivencia' },
      { type: 'checkbox', id: 'gendersId.38', label: 'Telenovela' },
      { type: 'checkbox', id: 'gendersId.43', label: 'Thriller' },
      { type: 'checkbox', id: 'gendersId.44', label: 'Tragedia' },
      { type: 'checkbox', id: 'gendersId.59', label: 'Transmigración' },
      { type: 'checkbox', id: 'gendersId.45', label: 'Vampiros' },
      { type: 'checkbox', id: 'gendersId.51', label: 'Venganza' },
      { type: 'checkbox', id: 'gendersId.35', label: 'Vida Escolar' },
      { type: 'checkbox', id: 'gendersId.54', label: 'Video Juegos' },
    ],
  },
  {
    type: 'group',
    id: 'state',
    label: 'Estado',
    filters: [
      { type: 'checkbox', id: 'state.1', label: 'En emisión' },
      { type: 'checkbox', id: 'state.2', label: 'En pausa' },
      { type: 'checkbox', id: 'state.3', label: 'Abandonado' },
      { type: 'checkbox', id: 'state.4', label: 'Finalizado' },
    ],
  },
  {
    type: 'group',
    id: 'origin',
    label: 'Origen',
    filters: [
      { type: 'checkbox', id: 'origin.2', label: 'Manhwa' },
      { type: 'checkbox', id: 'origin.3', label: 'Manhua' },
      { type: 'checkbox', id: 'origin.4', label: 'Manga' },
      { type: 'checkbox', id: 'origin.1', label: 'Webtoon' },
      { type: 'checkbox', id: 'origin.9', label: 'Novela' },
      { type: 'checkbox', id: 'origin.5', label: 'Manhwa +19' },
      { type: 'checkbox', id: 'origin.6', label: '+19 Sin Censura' },
      { type: 'checkbox', id: 'origin.7', label: 'BL Sin Censura' },
      { type: 'checkbox', id: 'origin.8', label: 'Manhwa BL' },
      { type: 'checkbox', id: 'origin.10', label: 'Manhua BL' },
    ],
  },
];
