import type { Filter } from '@matane/extension-sdk';

export const FILTERS: Filter[] = [
  {
    type: 'select',
    id: 'genre',
    label: 'Géneros',
    default: '',
    options: [
      { label: '<Seleccionar>', value: '' },
      { label: 'Accion', value: 'accion' },
      { label: 'Adulto', value: 'adulto' },
      { label: 'Artes Marciales', value: 'artes-marciales' },
      { label: 'Acontesimientos de la Vida', value: 'acontesimientos-de-la-vida' },
      { label: 'Bakunyuu', value: 'bakunyuu' },
      { label: 'Gore', value: 'gore' },
      { label: 'Gender Bender', value: 'gender-bender' },
      { label: 'Humor', value: 'humor' },
      { label: 'Harem', value: 'harem' },
      { label: 'Hentai', value: 'hentai' },
      { label: 'Horror', value: 'horror' },
      { label: 'Historico', value: 'historico' },
      { label: 'Josei', value: 'josei' },
      { label: 'Loli', value: 'loli' },
      { label: 'Light', value: 'light' },
      { label: 'Lucha Libre', value: 'lucha-libre' },
      { label: 'Manga', value: 'manga' },
      { label: 'Mecha', value: 'mecha' },
      { label: 'Magia', value: 'magia' },
      { label: 'Manhwa', value: 'manhwa' },
      { label: 'Manhua', value: 'manhua' },
      { label: 'Mature', value: 'mature' },
      { label: 'Misterio', value: 'misterio' },
      { label: 'Mutantes', value: 'mutantes' },
      { label: 'Novela', value: 'novela' },
      { label: 'OneShot', value: 'oneshot' },
      { label: 'Psicologico', value: 'psicologico' },
      { label: 'Romance', value: 'romance' },
      { label: 'Recuentos de la vida', value: 'recuentos-de-la-vida' },
      { label: 'Smut', value: 'smut' },
      { label: 'Shojo', value: 'shojo' },
      { label: 'Shonen', value: 'shonen' },
      { label: 'Seinen', value: 'seinen' },
      { label: 'Shoujo', value: 'shoujo' },
      { label: 'Shounen', value: 'shounen' },
      { label: 'Suspenso', value: 'suspenso' },
      { label: 'School Life', value: 'school-life' },
      { label: 'SuperHeroes', value: 'superheroes' },
      { label: 'Supernatural', value: 'supernatural' },
      { label: 'Slice of Life', value: 'slice-of-life' },
      { label: 'Super Poderes', value: 'super-poderes' },
      { label: 'Torneo', value: 'torneo' },
      { label: 'Tragedia', value: 'tragedia' },
      { label: 'Transexual', value: 'transexual' },
      { label: 'Vampiros', value: 'vampiros' },
      { label: 'Violencia', value: 'violencia' },
      { label: 'Vida Pasadas', value: 'vida-pasadas' },
      { label: 'Vida Cotidiana', value: 'vida-cotidiana' },
      { label: 'Vida de Escuela', value: 'vida-de-escuela' },
      { label: 'Webtoon', value: 'webtoon' },
      { label: 'Yaoi', value: 'yaoi' },
      { label: 'Yuri', value: 'yuri' },
      { label: 'Sobrenatural', value: 'sobrenatural' },
      { label: 'Drama', value: 'drama' },
      { label: 'Ecchi', value: 'ecchi' },
      { label: 'Comedia', value: 'comedia' },
      { label: 'Aventura', value: 'aventura' },
      { label: 'Fantasia', value: 'fantasia' },
      { label: 'Demonios', value: 'demonios' },
      { label: 'Superpoderes', value: 'superpoderes' },
      { label: 'Deporte', value: 'deporte' },
      { label: 'Ciencia Ficcion', value: 'ciencia-ficcion' },
      { label: 'Supervivencia', value: 'supervivencia' },
      { label: 'Crimen', value: 'crimen' },
      { label: 'Reencarnación', value: 'reencarnacion' },
      { label: 'Género Bender', value: 'genero-bender' },
      { label: 'Apocaliptico', value: 'apocaliptico' },
      { label: 'Familia', value: 'familia' },
      { label: 'Militar', value: 'militar' },
      { label: 'Guerra', value: 'guerra' },
      { label: 'Realidad', value: 'realidad' },
      { label: 'Animación', value: 'animacion' },
      { label: 'Musica', value: 'musica' },
      { label: 'Samurái', value: 'samurai' },
      { label: 'Historia', value: 'historia' },
      { label: 'Thriller', value: 'thriller' },
      { label: 'Girls Love', value: 'girls-love' },
      { label: 'Zombies', value: 'zombies' },
      { label: 'Netorare', value: 'netorare' },
      { label: 'Boys Love', value: 'boys-love' },
      { label: 'Transmigración', value: 'transmigracion' },
      { label: 'Regresion', value: 'regresion' },
      { label: 'Harem Inverso', value: 'harem-inverso' },
      { label: 'Moderno', value: 'moderno' },
      { label: 'Sistema', value: 'sistema' },
      { label: 'Venganza', value: 'venganza' },
      { label: 'Amateur', value: 'amateur' },
      { label: 'Parodia', value: 'parodia' },
    ],
  },
  {
    type: 'select',
    id: 'alphabetico',
    label: 'Alfabético',
    default: '',
    options: [
      { label: '<Seleccionar>', value: '' },
      { label: 'Other', value: 'Other' },
      { label: 'A', value: 'a' },
      { label: 'B', value: 'b' },
      { label: 'C', value: 'c' },
      { label: 'D', value: 'd' },
      { label: 'E', value: 'e' },
      { label: 'F', value: 'f' },
      { label: 'G', value: 'g' },
      { label: 'H', value: 'h' },
      { label: 'I', value: 'i' },
      { label: 'J', value: 'j' },
      { label: 'K', value: 'k' },
      { label: 'L', value: 'l' },
      { label: 'M', value: 'm' },
      { label: 'N', value: 'n' },
      { label: 'O', value: 'o' },
      { label: 'P', value: 'p' },
      { label: 'Q', value: 'q' },
      { label: 'R', value: 'r' },
      { label: 'S', value: 's' },
      { label: 'T', value: 't' },
      { label: 'U', value: 'u' },
      { label: 'V', value: 'v' },
      { label: 'W', value: 'w' },
      { label: 'X', value: 'x' },
      { label: 'Y', value: 'y' },
      { label: 'Z', value: 'z' },
    ],
  },
  {
    type: 'select',
    id: 'listacompletas',
    label: 'Lista Completa',
    default: '',
    options: [
      { label: '<Seleccionar>', value: '' },
      { label: 'Lista Comis', value: 'comic' },
      { label: 'Lista Novelas', value: 'novela' },
    ],
  },
];
