export const GENRES: [string, string][] = [
  ['Todos', ''],
  ['+19', '1'],
  ['Acción', '2'],
  ['Adulto', '3'],
  ['Apocalíptico', '4'],
  ['Aventura', '5'],
  ['BDSM', '6'],
  ['BL', '7'],
  ['Ciencia Ficción', '8'],
  ['Comedia', '9'],
  ['Crimen', '10'],
  ['Demonios', '11'],
  ['Deportes', '12'],
  ['Descensurado', '13'],
  ['Drama', '14'],
  ['Ecchi', '15'],
  ['Familia', '16'],
  ['Fantasía', '17'],
  ['Gender Bender', '18'],
  ['GL', '19'],
  ['Gogogo', '20'],
  ['Harem', '21'],
  ['Histórico', '22'],
  ['Horror', '23'],
  ['Isekai', '24'],
  ['Josei', '25'],
  ['Magia', '26'],
  ['Mazmorras', '27'],
  ['Militar', '28'],
  ['Misterio', '29'],
  ['Omegaverse', '30'],
  ['Psicológico', '31'],
  ['Reencarnación', '32'],
  ['Regresión', '33'],
  ['Romance', '34'],
  ['Seinen', '35'],
  ['Shoujo', '36'],
  ['Shounen', '37'],
  ['Sistemas', '38'],
  ['Smut', '39'],
  ['Sobrenatural', '40'],
  ['Soft BL', '41'],
  ['Supervivencia', '42'],
  ['Terror Psicológico', '43'],
  ['Thriller', '44'],
  ['Tragedia', '45'],
  ['Trasmigración', '46'],
  ['Vampiros', '47'],
  ['Venganza', '48'],
  ['Vida cotidiana', '49'],
  ['Vida escolar', '50'],
  ['Videojuegos', '51'],
  ['Wuxia', '52'],
];

export const ORDERS: [string, string][] = [
  ['Alfabético A-Z', 'name'],
  ['Más recientes', 'recent'],
  ['Más populares', 'popular'],
  ['Mejor calificados', 'rating'],
];
