import {
  type Chapter,
  type Filter,
  type FilterState,
  type HtmlElement,
  type MangaDetails,
  type MangaPage,
  type MangaSummary,
  type Page,
  defineExtension,
} from '@matane/extension-sdk';
import { USER_AGENT, absoluteUrl, hostOf, relativeUrl } from './common/utils';

const BASE_URL = 'https://kingcomix.com';
const headers = { 'User-Agent': USER_AGENT, Referer: `${BASE_URL}/` };

const CATEGORIES: [string, string][] = [
  ['Any', ''],
  ['3D Porn Comics', '3d-porn-comics-xxx'],
  ['Adventure Time Porn', 'adventure-time'],
  ['American Dad Porn', 'american-dad-xx-porn-comix'],
  ['Attack on Titan Hentai', 'attack-on-titan-hentai'],
  ['Ben 10 Porn Comics', 'ben-10-porn-comics-v1'],
  ['Chainsaw Man Porn Comics', 'porn-chainsaw-man-porn-comics'],
  ['Dragon Ball Porn', 'dragon-ball-z-porn-comics-v1'],
  ['Exclusive', 'exclusive'],
  ['Furry Porn Comics', 'porn-comic-furry'],
  ['Hentai Manga', 'xxxx-manga'],
  ['Interracial Porn', 'interracial-porn-comix2-xxx'],
  ['Kim Possible Porn', 'kim-possible-porn1'],
  ['LoL Hentai', 'lol-hentai-xxx-comics1'],
  ['My Hero Academia Hentai', 'hero-academia-porn-comic-v1'],
  ['Naruto Hentai', 'naruto-hentai-comic4'],
  ['One Piece Hentai', 'one-piece-hentai-v2'],
  ['Palcomix', 'palcomix'],
  ['Pokemon Porn', 'pokemon-porn-comics-v1'],
  ['Porn Comics', 'porn-c0mics'],
  ['Princess Peach Porn', 'princess-peach-porn-xxx'],
  ['Rick and Morty Porn Comics', 'rick-and-morty-porn-comics'],
  ['Simpsons Porn', 'simpsons-xxx-porn-comics'],
  ['Sonic Porn Comics', 'sonic_porn-comics'],
  ['Sword Art Online Hentai', 'sword-art-online-xxx-hentai1'],
  ['Teen Titans Porn', 'teen-titans-porn-v1'],
];

const TAGS: [string, string][] = [
  ['Any', ''],
  ['Aarokira', 'aarokira'],
  ['Accel Art', 'accel-art'],
  ['Aerith Hentai', 'aerith-hentai'],
  ['Afrobull', 'afrobull'],
  ['agent aika', 'agent-aika'],
  ['Ahri', 'ahri'],
  ['Ahri Hentai', 'ahri-hentai'],
  ['Ahsoka', 'ahsoka'],
  ['Akali Hentai', 'akali-hentai1'],
  ['Alien Girl', 'alien-girl'],
  ['American Dragon', 'american-dragon'],
  ['Amethyst', 'amethyst'],
  ['Amity Blight', 'amity-blight'],
  ['Among Us', 'among-us'],
  ['Amphibia Porn', 'amphibia-porn'],
  ['Amy', 'amy'],
  ['Amy Rose Hentai', 'amy-rose-hentai'],
  ['Amy Wong', 'amy-wong'],
  ['Anal', 'anal'],
  ['Anall', 'anall'],
  ['Android 18 Hentai', 'android_18_xxx-hentai'],
  ['Android 21 Hentai', 'android-21-hentai-xxx'],
  ['Animal Crossing', 'animal-crossing-hentai-v1'],
  ['Animated', 'animated'],
  ['Ankha', 'ankha'],
  ['Ann Possible', 'ann-possible'],
  ['Arabatos', 'arabatos'],
  ['Area', 'area'],
  ['Aroma Sensei', 'aroma-sensei'],
  ['Ashe Hentai', 'ashe-hentai'],
  ['Asuka Hentai', 'asuka-henta1'],
  ['Asuna Hentai', 'asuna-xxx-hentai'],
  ['Atlantis The Lost Empire', 'atlantis-the-lost-empire'],
  ['Atomic Heart Porn', 'atomic-heart-porn'],
  ['Avatar Hentai', 'avatar-hentai-v1'],
  ['Avengers', 'avengers'],
  ['Batgirl', 'batgirl'],
  ['Batman Porn Comics', 'batman-porn-comics-xxx'],
  ['Bayonetta', 'bayonetta'],
  ['BDSM', 'bdsm'],
  ['Beast Boy', 'beast-boy'],
  ['Big As', 'big-as'],
  ['Big Ass', 'big-ass'],
  ['Big Black Cock', 'big-black-cock'],
  ['Big Boobs', 'big-boobs-xxx'],
  ['Big Breasts', 'big-breasts-hentai'],
  ['Big Cock', 'big-cock'],
  ['Big Dick', 'big-dick'],
  ['Big Hero 6', 'big-hero-6-porn'],
  ['Big Tits', 'big-tit'],
  ['Bigdad', 'bigdad'],
  ['Bioshock Porn', 'bioshock-porn'],
  ['Black Clover Porn', 'black-clover-porn-xxx'],
  ['blackfire', 'blackfire'],
  ['Blacknwhite', 'blacknwhite'],
  ['Blaze', 'blaze'],
  ['Bleach Hentai', 'bleach-porn-comics-xxx'],
  ['Bloodborne', 'bloodborne'],
  ['Blowjob', 'blowjob'],
  ['Blue Archive', 'blue-archive'],
  ['Boa Hancock Hentai', 'boa-hancock-hentai-xxx1'],
  ['Boruto', 'boruto'],
  ['Botbot', 'botbot'],
  ['Bowsette Hentai', 'bowsette-hentai1'],
  ['Brain Dead 13 Porn', 'brain-dead-13-porn'],
  ['Brandy and mr Whiskers', 'brandy-and-mr-whiskers'],
  ['Briar Hentai', 'briar-hentai'],
  ['Bulma Hentai', 'bulma-h3ntaix'],
  ['Bunny Girl', 'bunny-girl'],
  ['Carmelita', 'carmelita'],
  ['carrot', 'carrot'],
  ['Catgirl', 'catgirl'],
  ['Catunder', 'catunder'],
  ['Caulifla Hentai', 'caulifla-hentai'],
  ['chainsaw man porn comic', 'chainsaw-man-porn-comic'],
  ['Chara', 'chara'],
  ['Cheelai Hentai', 'cheelai-hentai'],
  ['Cherry Road Porn Comics', 'cherry-road-porn-comics'],
  ['Chi-Chi Hentai', 'chi-chi_hentai'],
  ['Chloe', 'chloe'],
  ['ChoChoX', 'chochox'],
  ['Chun-Li', 'chun-li'],
  ['Coco Bandicoot Hentai', 'coco-bandicoot-hentai'],
  ['Code Lyoko', 'code-lyoko'],
  ['Connie Maheswaran', 'connie-maheswaran'],
  ['Cookie Run Porn', 'cookie-run-porn'],
  ['Cortana Porn', 'cortana-porn'],
  ['Crash Bandicoot', 'crash-bandicoot-porn'],
  ['CrazyDad3D', 'crazydad3d'],
  ['Cream the Rabbit', 'cream-the-rabbit'],
  ['CrockComix', 'crockcomix'],
  ['Crossdressing', 'crossdressing'],
  ['Cumshot', 'cumshot'],
  ['Cunnilingus', 'cunnilingus'],
  ['Cuphead Hentai', 'cuphead-hentai'],
  ['Cyberpunk Edgerunners Porn', 'cyberpunk-edgerunners-p0rn-comics'],
  ['Daisy Hentai', 'daisy-hentai'],
  ['Dandadan Hentai', 'dandadan-comic2-hentai'],
  ['Danganronpa', 'danganronpa'],
  ['Danny Phantom Porn', 'danny-phantom_porn-comics'],
  ['Daphne Hentai', 'daphne-hentai'],
  ['Dark Souls', 'dark-souls'],
  ['Darkstalkers Porn', 'darkstalkers-porn'],
  ['Dawn Hentai', 'dawn-hentai'],
  ['DC Porn', 'dc-porn'],
  ['Deadpool', 'deadpool'],
  ['Dee Dee', 'dee-dee'],
  ['Deepthroat', 'deepthroat'],
  ['Deku', 'deku'],
  ['Deltarune Porn', 'deltarune-porn'],
  ['Demon Girl', 'demon-girl'],
  ['Demon Slayer Nezuko Porn', 'demon-slayer-nezuko-porn1'],
  ['Demon Slayer Porn', 'demon-slayer-porn-comic1-xxx'],
  ['Devil May Cry', 'devil-may-cry'],
  ['Devvil May Cry Porn', 'devvil-may-cry-porn'],
  ['Dexter Mom Hentai', 'dexter-mom-hentai1'],
  ['Dexter Porn Comics', 'dexter-porn-comics'],
  ['Diane', 'diane'],
  ['Digimon XXX', 'digimon-xxx'],
  ['Dipper', 'dipper'],
  ['Diva Hentai', 'diva-hentai'],
  ['Doom', 'doom'],
  ['Dora', 'dora'],
  ['Double Anal', 'double-anal'],
  ['Double Penetration', 'double-penetration'],
  ['Dr. Stone', 'dr-stone-x'],
  ['Dragon Quest Porn', 'dragon-quest-porn'],
  ['Drah Navlag', 'drah-navlag'],
  ['Dsan', 'dsan'],
  ['dungeon and dragons', 'dungeon-and-dragons'],
  ['Ed Edd n Eddy Porn', 'ed-edd-n-eddy-porn'],
  ['Elden Ring', 'elden-ring'],
  ['Elf', 'elf'],
  ['Elizabeth Liones porn', 'elizabeth-liones-porn'],
  ['Elsa', 'elsa-hentai'],
  ['Emma Frost', 'emma-frost'],
  ['Epic Seven Hentai', 'epic-seven-hentai'],
  ['Ero Mantic', 'ero-mantic'],
  ['Evangelion Hentai', 'henta1-evangeli0n'],
  ['Evee', 'evee'],
  ['Evelynn', 'evelynn'],
  ['Exclusive', 'exclusive'],
  ['Fairy Tail', 'fairy-tail-hentai-v0'],
  ['Fallout XXX', 'fallout-xxx-hentai'],
  ['Family Guy Porn Comics', 'family-guy-porn_comix'],
  ['Fate Grand Order Hentai', 'fate-grand-order-hentai-v0'],
  ['Feith Noir', 'feith-noir'],
  ['Felsala', 'felsala'],
  ['Final Fantasy Hentai', 'final-fantasy-hentai-v2'],
  ['Finn', 'finn'],
  ['Fiona', 'fiona'],
  ['Fiora', 'fiora'],
  ['Fire Emblem', 'fire-emblem'],
  ["five nights at freddy's Porn", 'five-nights-at-freddys-porn'],
  ['Flame Princess', 'flame-princess'],
  ['Footjob', 'footjob'],
  ['Fortnite', 'fortnite'],
  ['Foster\u2019s Home for Imaginary Friends Porn', 'fosters-home-for-imaginary-friends-porn'],
  ['Francine Porn Comics', 'francine-porn-comics'],
  ['Frankie Foster Hentai', 'frankie-foster-hentai'],
  ['Fred Perry', 'fred-perry'],
  ['Frieren Porn', 'frieren-porn'],
  ['Frozen', 'frozen'],
  ['Fubuki Hentai', 'fubuki-hentai'],
  ['Full Color', 'full-color-comic'],
  ['FunsexyDB', 'funsexydb'],
  ['Furret El Furro', 'furret-el-furro'],
  ['Futa Comic', 'futanari-comic-xxx'],
  ['Futurama Porn Comics', 'futurama_porn-c0mics1'],
  ['Gansoman', 'gansoman'],
  ['Gardevoir Hentai', 'gardevoir-hentaix'],
  ['Garnet Hentai', 'garnet-hentai'],
  ['gay porn comics', 'porn-comics-gay'],
  ['Gemma Hentai', 'gemma-hentai'],
  ['Gender Bender', 'gender-bender'],
  ['Genshin Impact Porn', 'genshin-impact-p0rnx'],
  ['Gine Hentai', 'gine-hentai'],
  ['Girls und Panzer Hentai', 'girls-und-panzer_hentai'],
  ["Girls' Frontline Hentai", 'girls-frontline-hentai'],
  ['Glitch Techs', 'glitch-techs'],
  ['Glory Hole', 'glory-hole'],
  ['Goblin', 'goblin'],
  ['Goku', 'goku'],
  ['gold digger', 'gold-digger'],
  ['Granblue Fantasy', 'granblue-fantasy'],
  ['Gravity Falls Porn', 'gravity-falls-porn-comics'],
  ['Great Fairy Hentai', 'great-fairy-hentai'],
  ['Greendogg', 'greendogg'],
  ['Guilty Gear', 'guilty-gear'],
  ['Gumball', 'gumball'],
  ['Gwen', 'gwen'],
  ['Gwen Stacy', 'gwen-stacy'],
  ['GygerBeen', 'gygerbeen'],
  ['Hagfish', 'hagfish'],
  ['Haikon Knight', 'haikon-knight'],
  ['Halo', 'halo'],
  ['Handjob', 'handjob'],
  ['Harley Quinn', 'harley-quinn'],
  ['Harry Potter', 'harry-potter'],
  ['Hatsune Miku Hentai', 'hatsune-miku-hentai'],
  ['Hazbin Hotel', 'hazbin-hotel-pornx'],
  ['Hekapoo', 'hekapoo-hentai'],
  ['Helluva Boss Porn', 'helluva-boss-comics-xxx'],
  ['Hermione Granger', 'hermione-granger'],
  ['Hermit Moth Hentai', 'hermit-moth-hentai'],
  ['HermitMoth', 'hermitmoth'],
  ['Hey Arnold', 'hey-arnold'],
  ['Highschool DxD', 'highschool-dxd'],
  ['Hilda', 'hilda'],
  ['Hilda Porn', 'hilda-porn'],
  ['Himiko Toga Hentai', 'himiko-toga-hentai'],
  ['Hinata Hentai', 'hinata-hentai-xxx2'],
  ['Honey Lemon Hentai', 'honey-lemon-hentai'],
  ['Hornyx', 'hornyx'],
  ['Hot Step Sister', 'hot-step-sister'],
  ['Hotel Transylvania Porn Comics', 'hotel_transylvania-porn-comics'],
  ['Huge Breasts', 'huge-breasts'],
  ['Ice Queen Hentai', 'ice-queen-hentai'],
  ['Impa Hentai', 'impa-hentai'],
  ['Incestibles', 'incestibles'],
  ['Incognitymous', 'incognitymous-comic'],
  ['Ino', 'ino'],
  ['Ino Hentai', 'ino-hentai-xxx'],
  ['Inside Out', 'inside-out'],
  ['Inspector Gadget', 'inspector-gadget'],
  ['Inuyuru', 'inuyuru'],
  ['Invader Zim Porn', 'invader-zim-porn'],
  ['INVINCIBLE Porn', 'invincible-porn'],
  ['Irelia Hentai', 'irelia-hentai'],
  ['IS Infinite Stratos', 'is-infinite-stratos'],
  ['Isabelle', 'isabelle'],
  ['Itsuka Kendo Hentai', 'itsuka-kendo-hentai'],
  ['Jack and Daxter', 'jack-and-daxter'],
  ['Jackie Lynn', 'jackie-lynn'],
  ['Jaguar', 'jaguar'],
  ['Jaiden XXX', 'jaiden-xxx'],
  ['Janna', 'janna'],
  ['Jasmine', 'jasmine'],
  ['JDseal', 'jdseal'],
  ['Jenny Hentai', 'jenny-hentai'],
  ['Jessica Rabbit', 'jessica-rabbit'],
  ['Jessie Porn', 'jessie-porn'],
  ['Jill Valentine', 'jill-valentine'],
  ['Jimmy Neutron', 'jimmy-neutron'],
  ['Jinx', 'jinx'],
  ['Jinx Hentai', 'jinx-hentai-xxx-v2'],
  ['Jirou Hentai', 'jirou_hentai'],
  ['Jlullaby', 'jlullaby'],
  ['Johnny Test', 'johnny-test'],
  ['Jujutsu Kaisen', 'jujutsu-kaisen'],
  ['Justice League', 'justice-league'],
  ['JZerosk', 'jzerosk'],
  ['Kairi', 'kairi'],
  ['Kale Hentai', 'kale-hentai-xxx'],
  ['Kantai Collection Hentai', 'kantai-collection-hentai'],
  ['Katarina Hentai', 'katarina-hentai'],
  ['Kefla Hentai', 'kefla-hentai'],
  ['Kid Icarus', 'kid-icarus'],
  ['Kill la Kill', 'kill-la-kill-hentai'],
  ['Kim Possible', 'kim-possible-porn1'],
  ['kingdom hearts', 'kingdom-hearts'],
  ['Kinkymation', 'kinkymation-hentai'],
  ['Kirlia Hentai', 'kirlia-hentai'],
  ['Kiryuin Satsuki Hentai', 'kiryuin-satsuki-hentai'],
  ['Kogeikun', 'kogeikun'],
  ['Lady Dimitrescu Porn', 'lady_dimitrescu-porn'],
  ['Lady Dmittrescu', 'lady-dmittrescu'],
  ['Lapis Lazuli', 'lapis-lazuli'],
  ['Lara Croft', 'lara-croft'],
  ['Leela Porn', 'leela-porn'],
  ['Leona', 'leona'],
  ['Lesbians', 'lesbians'],
  ['Lilo and Stitch', 'lilo-and-stitch'],
  ['Lina Inverse', 'lina-inverse'],
  ['Lisa Simpson Porn', 'lisa-simpson-porn'],
  ['Lissandra', 'lissandra'],
  ['Little Nightmares', 'little-nightmares'],
  ['Little Nightmares Porn', 'little-nightmares-porn'],
  ['Little Witch Academia', 'little-witch-academia'],
  ['Lola Bunny', 'lola-bunny'],
  ['Looney Tunes Porn', 'looney-tunes-porn'],
  ['Lori Loud Porn', 'lori-loud-porn'],
  ['Luna Loud', 'luna-loud'],
  ['Lux', 'lux'],
  ['Luz Noceda', 'luz-noceda'],
  ['Mabel', 'mabel'],
  ['Macergo', 'macergo'],
  ['Madeline Fenton', 'madeline-fenton'],
  ['Mai Hentai', 'mai-hentai'],
  ['Malefica', 'malefica'],
  ['Maleficient', 'maleficient'],
  ['Mana World', 'mana-world'],
  ['Manaworld', 'manaworld'],
  ['Marceline', 'marceline'],
  ['Marco Diaz', 'marco-diaz'],
  ['Marge Simpson Porn', 'marge-simpson-porn-xxx'],
  ['Mario Bros', 'mario-bros'],
  ['Marvel', 'marvel'],
  ['Marvel Rivals Porn', 'marvel-rivals-porn'],
  ['Mass Effect Porn', 'mass-effect-porn'],
  ['Masturbation', 'masturbation'],
  ['May Hentai', 'may-hentai-xxx'],
  ['Meego', 'meego'],
  ['Meg Griffin', 'meg-griffin'],
  ['Mega Man', 'mega-man'],
  ['Mei Hatsume Hentai', 'mei-hatsume-hentai'],
  ['Mei Hentai', 'mei-hentai'],
  ['Melkor Mancin', 'melkor-mancin'],
  ['MelkorMancin', 'melkormancin'],
  ['Mercy Hentai', 'mercy-hentai'],
  ['Metroid', 'metroid'],
  ['Midna Hentai', 'midna-hentai'],
  ['Mif', 'mif'],
  ['Mifl', 'mifl'],
  ['Mikasa Hentai', 'mikasa-henta1'],
  ['Miko', 'miko'],
  ['Miles', 'miles'],
  ['Miles Morales Porn Comics', 'miles-morales-porn-comics'],
  ['Milf', 'milf-xxx'],
  ['Milfs', 'milfs'],
  ['Milk', 'milk'],
  ['Milky Bunny', 'milky-bunny'],
  ['Millie', 'millie'],
  ["Milo Murphy's Law Porn", 'milo-murphys-law-porn'],
  ['Mina Ashido Hentai', 'mina-ashido-hentai1'],
  ['Minako Aino', 'minako-aino'],
  ['Minecraft Porn', 'minecraft-porn'],
  ['Mineta', 'mineta'],
  ['Miraculous Ladybug', 'miraculous-ladybug'],
  ['Misato Katsuragi Hentai', 'misato-katsuragi-hentai'],
  ['Miss Heed', 'miss-heed'],
  ['Misty Hentai', 'misty-hentai'],
  ['Mitsuki Hentai', 'mitsuki-hentai'],
  ['Mob Psycho 100', 'mob-psycho-100'],
  ['Mobile Suit Gundam', 'mobile-suit-gundam'],
  ['Momo Hentai', 'momo_hentai'],
  ['Mona', 'mona'],
  ['Monster Girl', 'monster-girl'],
  ['monster hunter', 'monster-hunter'],
  ['Morgana Hentai', 'morgana-hentai'],
  ['Mossy Froot', 'mossy-froot'],
  ['Mr. Jean Gobax', 'mr-jean-gobax'],
  ['Mr.E', 'mr-e'],
  ['My Bad Bunny', 'my-bad-bunny'],
  ['My LIfe as a Teenage Robot', 'my-life-as-a-teenage-robot'],
  ['My Little Pony Porn Comics', 'porn-comic-xxx-my-little-pony1'],
  ['Nami Hentai', 'nami-xxx-hentai-1'],
  ['Nana Shimura Hentai', 'nana-shimura-hentai'],
  ['Neeko', 'neeko'],
  ['Nejire Hado', 'nejire-hado'],
  ['Nemona Hentai', 'nemona-hentai'],
  ['Nemuri Kayama Hentai', 'nemuri-kayama-hentai'],
  ['NGTVisualStudio', 'ngtvisualstudio'],
  ['Nico Robin Hentai', 'nico-robin-xxx-hentai2'],
  ['Nicole Watterson', 'nicole-watterson'],
  ['Nier Automata', 'nier-automata'],
  ['Nisego', 'nisego'],
  ['Oban Star Racers', 'oban-star-racers'],
  ['Ochako Uraraka', 'ochako-uraraka'],
  ["OK K.O.! Let's Be Heroes Porn", 'ok-k-o-lets-be-heroes-porn'],
  ['One Punch Man', 'comic-hentai-one-punch-man-porn'],
  ['OnGoing', 'ongoing'],
  ['Ousama Ranking', 'ousama-ranking'],
  ['Overwatch Porn', 'overwatch-porn'],
  ['Pacifica Porn', 'pacifica-porn'],
  ['Palutena Hentai', 'palutena-hentai'],
  ['Panchy', 'panchy'],
  ['Paya Hentai', 'paya-hentai'],
  ['Peach Hentai', 'peach-hentai'],
  ['Pearl', 'pearl'],
  ['Pedverse', 'pedverse'],
  ['Peg', 'peg'],
  ['Persona 2', 'persona-2'],
  ['Persona 3', 'persona-3'],
  ['Persona 4', 'persona-4-xxx'],
  ['persona 5', 'persona-5'],
  ['Phineas and Ferb', 'phineas-and-ferb'],
  ['Pink Pawg', 'pink-pawg'],
  ['Pokemon Scarlet', 'pokemon-scarlet'],
  ['PokuArts', 'pokuarts'],
  ['Pony Tsunotori Hentai', 'pony-tsunotori-hentai'],
  ['Poppy', 'poppy'],
  ['Porn Parody', 'porn-parody'],
  ['Princess Bubblegum', 'princess-bubblegum'],
  ['Princess Daisy', 'princess-daisy'],
  ['Princess Peach', 'princess-peach'],
  ['Prison School Hentai', 'prison-school-hentai'],
  ['Priyanka Hentai', 'priyanka-hentai'],
  ['Promare', 'promare'],
  ['Purah Hentai', 'purah-hentai'],
  ['Rainbow Mika', 'rainbow-mika'],
  ['Rainbow Six Siege Porn', 'rainbow-six-siege-porn'],
  ['Ranma Porn', 'ranma-porn-comic'],
  ['Ratchet and Clank Porn', 'ratchet-and-clank-porn'],
  ['Raven', 'raven'],
  ['Raven xxx', 'raven-hentaaii'],
  ['Razter', 'razter'],
  ['Rebecca Cyberpunk Porn', 'rebecca-cyberpunk-p0rn'],
  ['Rei Hentai', 'rei-hentai'],
  ['RelatedGuy', 'relatedguy-porn'],
  ['Rem Hentai', 'rem-hentai'],
  ['Renamon', 'renamon'],
  ['Resident Evil', 'resident-evil-porn'],
  ['Rezero Hentai', 'rezero-hentai'],
  ['Rick and Morty Porn Comics', 'rick_and-morty-porn-comics-xxx'],
  ['Riukykappa', 'riukykappa'],
  ['Riven', 'riven'],
  ['Rivet Hentai', 'rivet-hentai'],
  ['road to el dorado', 'road-to-el-dorado'],
  ['Rosalina Hentai', 'rosalina-hentai'],
  ['Rouge', 'rouge'],
  ['Roumgu', 'roumgu-xxx'],
  ['Rudolph', 'rudolph'],
  ['Rumi Usagiyama Hentai', 'rumi-usagiyama-hentai'],
  ['Sailor Moon Hentai', 'sailor-moon-hentai'],
  ['Sakura Hentai', 'sakura_h3ntai'],
  ['Sally', 'sally'],
  ['Samantha Manson', 'samantha-manson'],
  ['Samsung Sam Hentai', 'samsung-sam-hentai'],
  ['Samus Hentai', 'samus-hentai'],
  ['Sandy', 'sandy'],
  ['Sarada Hentai', 'sarada-hentai'],
  ['Scooby Doo Hentai', 'scooby-doo-hentai'],
  ['Seiko Hentai', 'seiko-hentai'],
  ['Seraphine', 'seraphine'],
  ['Sex Toys', 'sex-toys'],
  ['Shadbase', 'shadbase-comics'],
  ['Shantae', 'shantae-hentai'],
  ['She-Hulk', 'she-hulk-porn'],
  ['She-Ra and the Princesses of Power Porn', 'she-ra-and-the-princesses-of-power-porn'],
  ['Shego', 'shego'],
  ['shin-chan', 'shin-chan'],
  ['Sidney', 'sidney'],
  ['Sillygirl', 'sillygirl'],
  ['Six', 'six'],
  ['Skullgirls', 'skullgirls'],
  ['Small Tits', 'small-tits'],
  ['Smash Bros', 'smash-bros'],
  ['Sonic', 'sonic'],
  ['Soraka', 'soraka'],
  ['Soraka Hentai', 'soraka-hentai'],
  ['Soul Knight', 'soul-knight'],
  ['South Park', 'south-park'],
  ['Spectra', 'spectra'],
  ['spidergirl', 'spidergirl-xxx'],
  ['Spiderman Porn Comics', 'porn-comics-xxx-spiderman1'],
  ['Spinel', 'spinel'],
  ['Splatoon Porn Comics', 'splaton-porn-comic'],
  ['Spongebob Porn Comics', 'spongebob-porn-comics'],
  ['Spy x Family Porn', 'p0rn-spy-x-family'],
  ['Squirrel Girl Porn', 'squirrel-girl-porn'],
  ['Star Butterfly Porn', 'star-butterfly-porn'],
  ['Star Trek', 'star-trek'],
  ['Star vs The Forces of Evil', 'porn-comic-star-vs-the-forces-of-evil'],
  ['Star Wars', 'star-wars'],
  ['Starfire', 'starfire'],
  ['Steven Universe Porn Comics', 'steven-universe-porn_comics1'],
  ['StormFedeR', 'stormfeder-porn'],
  ['Street Fighter Porn', 'street-fighter-porn-comix1'],
  ['Strong Bana', 'strong-bana'],
  ['StrongBana', 'strongbana-porn'],
  ['Suguha Hentai', 'suguha-hentai'],
  ['Summer Hentai', 'summer-hentai'],
  ['Super Melons', 'super-melons'],
  ['Supergirl', 'supergirl'],
  ['Superman', 'superman-x'],
  ['Taboolicious', 'taboolicious'],
  ['Taimanin Asagi', 'taimanin-asagi'],
  ['Tatsumaki Hentai', 'tatsumaki-hentai-one-punch-mam'],
  ['Tawna', 'tawna'],
  ['Teacher', 'teacher'],
  ['Teen', 'teen'],
  ['Teenage Mutant Ninja Turtles Porn Comics', 'teenage-mutant-ninja-turtles-porn-comics'],
  ['Teens', 'teens'],
  ['Tenn', 'tenn'],
  ['Tentacles', 'tentacles'],
  ['Tenten Hentai', 'tenten-hentai'],
  ['the addams family', 'the-addams-family'],
  ['The Amazing Digital Circus', 'the-amazing-digital-circus'],
  ['The Amazing world of Gumball Porn Comics', 'amazing-world-of-gumball-porn-comixs'],
  ['The Arthman', 'tthe-arthman'],
  ['the elder scrolls', 'the-elder-scrolls'],
  ['The Fairly OddParents Porn', 'porn-comics-the-fairly-oddparents-xx'],
  ['The Grim Adventures of Billy & Mandy Porn', 'the-grim-adventures-of-billy-mandy-porn'],
  ['The grim adventures of Billy and Mandy', 'the-grim-adventures-of-billy-and-mandy'],
  ['The Idolmaster', 'the-idolmaster'],
  ['The Incredibles Porn', 'the-incredibles-porn_comics'],
  ['The Jetsons', 'the-jetsons'],
  ['The Last Airbender', 'the-last-airbender'],
  ['The Last of Us', 'the-last-of-us'],
  ['The Legend of Zelda Hentai', 'the-legend-of-zelda-p'],
  ['The Loud House', 'porn-comic-the-loud-house-sex'],
  ['The Owl House', 'porn-comics-the-owl-house'],
  ['the powerpuff girls', 'the-powerpuff-girls'],
  ['The proud family', 'the-proud-family'],
  ['The Ring', 'the-ring'],
  ['the seven deadly sins', 'the-seven-deadly-sins'],
  ['The Summoning Porn', 'the-summoning-porn'],
  ['The Sword In The Stone Porn Comics', 'the-sword-in-the-stone-porn-comics'],
  ['The Walking Dead', 'the-walking-dead'],
  ['The Witcher', 'the-witcher'],
  ['Thicc', 'thicc-xxx'],
  ['Three Houses', 'three-houses'],
  ['Tifa Hentai', 'tifa-hentai'],
  ['To Love-Ru Hentai', 'to-love-ru-hentai'],
  ['Tomb Raider', 'tomb-raider'],
  ['Tomgirl', 'tomgirl'],
  ['Toph Hentai', 'toph-hentai'],
  ['Total Drama', 'total-drama-porn-comic'],
  ['Totally Spies', 'porn-comics-totally-spies'],
  ['Touhou Project Hentai', 'touhou-project-hentaix'],
  ['Tracy Scops', 'tracy-scops'],
  ['Transformers Porn', 'transformers-porn'],
  ['Tricia Hentai', 'tricia-hentai'],
  ['Tsunade Hentai', 'tsunade_hentai'],
  ['Tsuyu Asui Hentai', 'tsuyu-asui-hentai'],
  ['Umbreon', 'umbreon'],
  ['Uncensored', 'uncensored'],
  ['Undertale', 'undertale'],
  ['Undyne', 'undyne'],
  ['Uraraka Hentai', 'uraraka-hentai-xxx'],
  ['Urbosa', 'urbosa'],
  ['Vados Hentai', 'vados-hentai'],
  ['Vanilla', 'vanilla'],
  ['Velma Hentai', 'velma-hentai'],
  ['VerComicsPorno', 'vercomicsporno'],
  ['Vicky', 'vicky'],
  ['Videl Hentai', 'videl-hentai1'],
  ['violet parr', 'violet-parr'],
  ['Wakfu Porn', 'wakfu-porn'],
  ['Wander Over Yonder', 'wander-over-yonder'],
  ['Warcraft', 'warcraft'],
  ['Warhammer porn', 'warhammer-porn'],
  ['Wendy', 'wendy'],
  ['Widowmaker', 'widowmaker'],
  ['Willow', 'willow'],
  ['Wonder Woman', 'xxx-wonder-woman'],
  ['World of Warcraft', 'world-of-warcraft'],
  ['WoW', 'wow'],
  ['x-men', 'x-men'],
  ['Xayah', 'xayah'],
  ['Xenoblade Chronicles 2 Hentai', 'xenoblade-chronicles-2-hentaix'],
  ['Xierra099', 'xierra099'],
  ['Y3DF', 'y3df'],
  ['Yamato Hentai', 'yamato-hentai'],
  ['Yu Takeyama Hentai', 'yu-takeyama-hentai'],
  ['Yu-Gi-Oh Hentai', 'yu-gi-oh-entai'],
  ['Yuri', 'yuri-hentai'],
  ['Zac', 'zac'],
  ['Zelda Hentai', 'zelda-hentai'],
  ['Zenless Zone Zero porn', 'zenless-zone-zero-porn'],
  ['Zoe', 'zoe'],
  ['Zootopia', 'zootopia'],
];

async function load(url: string): Promise<HtmlElement> {
  const response = await http.get(absoluteUrl(BASE_URL, url), { headers });
  return html.load(response.body, { baseUrl: response.url });
}

const image = (img: HtmlElement | null) => (img ? img.absUrl('data-src') || img.absUrl('src') || undefined : undefined);

async function list(path: string, page: number, query = ''): Promise<MangaPage> {
  const url = `${path}${page > 1 ? `page/${page}/` : ''}${query ? `?s=${encodeURIComponent(query)}` : ''}`;
  const document = await load(url);
  const items = document.select('div.entry, article.thumb-block').flatMap((el): MangaSummary[] => {
    const a = el.selectFirst('h2.information a, a[title]');
    if (!a) return [];
    return [
      {
        url: relativeUrl(a.absUrl('href') || a.attr('href') || ''),
        title: a.text() || a.attr('title') || '',
        thumbnailUrl: image(el.selectFirst('img')),
      },
    ];
  });
  const hasNextPage = document
    .select('.pagination a')
    .map((a) => Number.parseInt(a.text(), 10))
    .some((n) => n > page);
  return { items, hasNextPage };
}

const select = (id: string, label: string, options: [string, string][]): Filter => ({
  type: 'select',
  id,
  label,
  options: options.map(([l, v]) => ({ label: l, value: v })),
  default: '',
});

export default defineExtension({
  createSource: () => ({
    baseUrl: BASE_URL,
    getPopular: (page) => list('/', page),
    search(query: string, page: number, filters: FilterState): Promise<MangaPage> {
      if (query.trim()) return list('/', page, query.trim());
      const category = typeof filters.category === 'string' ? filters.category : '';
      const tag = typeof filters.tag === 'string' ? filters.tag : '';
      // Categories and tags cannot be combined; a category wins.
      if (category) return list(`/category/${category}/`, page);
      if (tag) return list(`/tag/${tag}/`, page);
      return list('/', page);
    },
    getFilters: (): Filter[] => [
      { type: 'header', label: 'Text search ignores filters.' },
      { type: 'header', label: 'Select EITHER a Category OR a Tag. If both are selected, Category takes priority.' },
      { type: 'separator' },
      select('category', 'Category', CATEGORIES),
      select('tag', 'Tag', TAGS),
    ],
    async getMangaDetails(manga: MangaSummary): Promise<MangaDetails> {
      const document = await load(manga.url);
      return {
        url: manga.url,
        title: document.selectFirst('h1.singleTitle-h1, h1.widget-title')?.text() || manga.title,
        author: document.selectFirst('meta[name=author]')?.attr('content') || undefined,
        genres: document.select('.caTotal .tagsPost a.taxLink').map((a) => a.text()),
        thumbnailUrl:
          document.selectFirst('meta[property=og:image]')?.attr('content') ||
          document.selectFirst('.entry-content img')?.absUrl('src') ||
          manga.thumbnailUrl,
        status: 'completed',
      };
    },
    async getChapters(manga: MangaSummary): Promise<Chapter[]> {
      const document = await load(manga.url);
      const date = Date.parse(document.selectFirst('meta[property=article:published_time]')?.attr('content') ?? '');
      return [{ url: manga.url, name: 'Chapter', uploadedAt: Number.isNaN(date) ? undefined : date }];
    },
    async getPages(chapter: Chapter): Promise<Page[]> {
      return (await load(chapter.url))
        .select('.entry-content img')
        .map((img, index) => ({ index, imageUrl: image(img) ?? '' }));
    },
    imageHeaders: () => headers,
    resolveUrl(url: string): MangaSummary | null {
      const match = /^https?:\/\/([^/?#]+)(\/[^?#]+)/i.exec(url.trim());
      if (!match || match[1]!.toLowerCase() !== hostOf(BASE_URL)) return null;
      return /^\/(category|tag|page)\//.test(match[2]!) ? null : { url: match[2]!, title: '' };
    },
    getWebUrl: (item) => absoluteUrl(BASE_URL, item.url),
  }),
});
