export const GENRES: [string, string][] = [
  ['18+', '18'],
  ['Adult', 'adult'],
  ['Big Boobs', 'big-boobs'],
  ['Boy Love', 'boy-love'],
  ['Cheating', 'cheating'],
  ['Comedy', 'comedy'],
  ['Cosplay', 'cosplay'],
  ['Dirty Old Man', 'dirty-old-man'],
  ['Drama', 'drama'],
  ['Ecchi', 'ecchi'],
  ['Fantasy', 'fantasy'],
  ['Full Color', 'full-color'],
  ['Furry', 'furry'],
  ['Game', 'game'],
  ['GangBang', 'gangbang'],
  ['Guro', 'guro'],
  ['Harem', 'harem'],
  ['Isekai', 'isekai'],
  ['Không che', 'khong-che'],
  ['Kinh Dị', 'kinh-di'],
  ['Loli', 'loli'],
  ['Loạn Luân', 'loan-luan'],
  ['Manga', 'manga'],
  ['Manhua', 'manhua'],
  ['Manhwa', 'manhwa'],
  ['Milf', 'milf'],
  ['Mind Break', 'mind-break'],
  ['NTR', 'ntr'],
  ['Netori', 'netori'],
  ['Ngôn Tình', 'ngon-tinh'],
  ['OneShot', 'oneshot'],
  ['Rape', 'rape'],
  ['Romance', 'romance'],
  ['School Life', 'school-life'],
  ['SchoolGirl', 'schoolgirl'],
  ['Seinen', 'seinen'],
  ['Shota', 'shota'],
  ['Shoujo ai', 'shoujo-ai'],
  ['Shoujo', 'shoujo'],
  ['Shounen ai', 'shounen-ai'],
  ['Siscon', 'siscon'],
  ['Slice Of Life', 'slice-of-life'],
  ['Tragedy', 'tragedy'],
  ['Tsundere', 'tsundere'],
  ['Yaoi', 'yaoi'],
  ['Yuri', 'yuri'],
];
