import type { Filter } from '@matane/extension-sdk';

export const FILTERS: Filter[] = [
  {
    type: 'select',
    id: 'type',
    label: 'Tipo',
    default: '',
    options: [
      { label: 'Todos', value: '' },
      { label: 'Manga', value: 'Manga' },
      { label: 'Manhwa', value: 'Manhwa' },
      { label: 'Manhua', value: 'Manhua' },
    ],
  },
];

export const GENRES: [string, string][] = [
  ['Acción', 'Acción'],
  ['Animación', 'Animación'],
  ['Apocalíptico', 'Apocalíptico'],
  ['Artes marciales', 'Artes marciales'],
  ['Automóviles', 'Automóviles'],
  ['Aventura', 'Aventura'],
  ['Boys Love', 'Boys Love'],
  ['Ciberpunk', 'Ciberpunk'],
  ['Ciencia Ficción', 'Ciencia Ficción'],
  ['Comedia', 'Comedia'],
  ['Crimen', 'Crimen'],
  ['Demonios', 'Demonios'],
  ['Deporte', 'Deporte'],
  ['Deportes', 'Deportes'],
  ['Doujinshi', 'Doujinshi'],
  ['Drama', 'Drama'],
  ['Ecchi', 'Ecchi'],
  ['Espacio exterior', 'Espacio exterior'],
  ['Extranjero', 'Extranjero'],
  ['Familia', 'Familia'],
  ['Fantasía', 'Fantasía'],
  ['Género Bender', 'Género Bender'],
  ['Girls Love', 'Girls Love'],
  ['Gore', 'Gore'],
  ['Guerra', 'Guerra'],
  ['Harem', 'Harem'],
  ['Historia', 'Historia'],
  ['Histórico', 'Histórico'],
  ['Horror', 'Horror'],
  ['Isekai', 'Isekai'],
  ['Josei', 'Josei'],
  ['Juegos', 'Juegos'],
  ['Locura', 'Locura'],
  ['Magia', 'Magia'],
  ['Mecha', 'Mecha'],
  ['Militar', 'Militar'],
  ['Misterio', 'Misterio'],
  ['Música', 'Música'],
  ['Niños', 'Niños'],
  ['Oeste', 'Oeste'],
  ['Parodia', 'Parodia'],
  ['Policía', 'Policía'],
  ['Policiaco', 'Policiaco'],
  ['Psicológico', 'Psicológico'],
  ['Realidad', 'Realidad'],
  ['Realidad Virtual', 'Realidad Virtual'],
  ['Recuentos de la vida', 'Recuentos de la vida'],
  ['Reencarnación', 'Reencarnación'],
  ['Romance', 'Romance'],
  ['Samurai', 'Samurai'],
  ['Seinen', 'Seinen'],
  ['Shoujo', 'Shoujo'],
  ['Shoujo Ai', 'Shoujo Ai'],
  ['Shounen', 'Shounen'],
  ['Sobrenatural', 'Sobrenatural'],
  ['Superpoderes', 'Superpoderes'],
  ['Supervivencia', 'Supervivencia'],
  ['Suspenso', 'Suspenso'],
  ['Telenovela', 'Telenovela'],
  ['Terror', 'Terror'],
  ['Thriller', 'Thriller'],
  ['Tragedia', 'Tragedia'],
  ['Traps', 'Traps'],
  ['Vampiros', 'Vampiros'],
  ['Vida escolar', 'Vida escolar'],
];
