export const TABS: [string, string][] = [
  ['General', 'general'],
  ['GL / Yuri', 'yuri'],
  ['BL / Yaoi', 'yaoi'],
  ['Doujinshis', 'doujinshi'],
];

export const GENRES: [string, string][] = [
  ['Todas las categorías', '0'],
  ['4-venida', '44'],
  ['A todo color', '38'],
  ['Acción', '14'],
  ['Adaptación', '13'],
  ['Adulto', '87'],
  ['Amor de chicas', '43'],
  ['Amor de chicos', '61'],
  ['Animales', '66'],
  ['Antología', '71'],
  ['Apocalipsis', '83'],
  ['Arreglarlo', '42'],
  ['Artes marciales', '7'],
  ['Autoeditado', '54'],
  ['Aventura', '15'],
  ['Cambio de sexo', '33'],
  ['Chicas magicas', '64'],
  ['Chicas monstruo', '22'],
  ['Ciencia ficción', '52'],
  ['Cocinando', '70'],
  ['Color del abanico', '80'],
  ['Color oficial', '69'],
  ['Comedia', '1'],
  ['Cómic web', '18'],
  ['Crimen', '97'],
  ['Culinario', '90'],
  ['Cultivación', '92'],
  ['Cyberpunk', '84'],
  ['Delincuentes', '12'],
  ['Delito', '76'],
  ['Demonios', '25'],
  ['Deportes', '68'],
  ['Dominó chino', '73'],
  ['Doujinshi', '65'],
  ['Drama', '2'],
  ['Ecchi', '3'],
  ['Extraterrestres', '75'],
  ['Fantasía', '16'],
  ['Fantasmas', '29'],
  ['Filosófico', '49'],
  ['Gore', '85'],
  ['Harem', '8'],
  ['Harem inverso', '81'],
  ['Hentai', '82'],
  ['Histórico', '28'],
  ['Horror', '51'],
  ['Incesto', '40'],
  ['Intercambio de género', '55'],
  ['Isekai', '11'],
  ['Jefe/Empleado', '88'],
  ['Juegos de vídeo', '58'],
  ['Juegos tradicionales', '72'],
  ['Loli', '35'],
  ['Mafia', '46'],
  ['Magia', '17'],
  ['Meca', '63'],
  ['Mecha', '53'],
  ['Médico', '50'],
  ['Militar', '36'],
  ['Misterio', '31'],
  ['Monstruos', '24'],
  ['Música', '78'],
  ['Ninja', '79'],
  ['Niños', '95'],
  ['Policía', '62'],
  ['Post-apocalíptico', '59'],
  ['Premiado', '21'],
  ['Psicológico', '26'],
  ['Realeza', '98'],
  ['Realidad virtual', '57'],
  ['Recuentos de la vida', '6'],
  ['Reencarnación', '9'],
  ['Romance', '4'],
  ['Samurai', '56'],
  ['Sangre', '27'],
  ['Shota', '32'],
  ['Shoujo Ai', '94'],
  ['Smut', '96'],
  ['Sobrenatural', '23'],
  ['Superhéroe', '74'],
  ['Supervivencia', '30'],
  ['Suspense', '48'],
  ['Suspenso', '67'],
  ['Tira larga', '37'],
  ['Trabajadores de oficina', '20'],
  ['Tragedia', '47'],
  ['Travestismo', '34'],
  ['Un trago', '39'],
  ['Vampiros', '41'],
  ['Venganza', '93'],
  ['Viaje en el tiempo', '19'],
  ['Vida escolar', '5'],
  ['Vida Laboral', '91'],
  ['Videojuegos', '86'],
  ['Villana', '45'],
  ['Violencia sexual', '10'],
  ['Wuxia', '77'],
  ['Yaoi', '89'],
  ['Zombis', '60'],
];
