export const GENRES: [string, string][] = [
  ['Action', 'action'],
  ['Adventure', 'adventure'],
  ['Anime', 'anime'],
  ['Chuyển Sinh', 'chuyen-sinh'],
  ['Cổ Đại', 'co-dai'],
  ['Comedy', 'comedy'],
  ['Comic', 'comic'],
  ['Cooking', 'cooking'],
  ['Doujinshi', 'doujinshi'],
  ['Drama', 'drama'],
  ['Fantasy', 'fantasy'],
  ['Gender Bender', 'gender-bender'],
  ['Historical', 'historical'],
  ['Horror', 'horror'],
  ['Live action', 'live-action'],
  ['Manga', 'manga'],
  ['Manhua', 'manhua'],
  ['Manhwa', 'manhwa'],
  ['Martial Arts', 'martial-arts'],
  ['Mecha', 'mecha'],
  ['Mystery', 'mystery'],
  ['Ngôn Tình', 'ngon-tinh'],
  ['Psychological', 'psychological'],
  ['Romance', 'romance'],
  ['School Life', 'school-life'],
  ['Sci-fi', 'sci-fi'],
  ['Shoujo', 'shoujo'],
  ['Shoujo Ai', 'shoujo-ai'],
  ['Shounen', 'shounen'],
  ['Shounen Ai', 'shounen-ai'],
  ['Slice of Life', 'slice-of-life'],
  ['Sports', 'sports'],
  ['Supernatural', 'supernatural'],
  ['Thiếu Nhi', 'thieu-nhi'],
  ['Tragedy', 'tragedy'],
  ['Trinh Thám', 'trinh-tham'],
  ['Truyện Màu', 'truyen-mau'],
  ['Truyện scan', 'truyen-scan'],
  ['Tu Tiên', 'tu-tien'],
  ['Webtoon', 'webtoon'],
  ['Xuyên Không', 'xuyen-khong'],
  ['Đam Mỹ', 'dam-my'],
];
