import type { Filter } from '@matane/extension-sdk';

export const FILTERS: Filter[] = [
  {
    type: 'select',
    id: 'alphabetic',
    label: 'Ordenar por',
    default: '',
    options: [
      { label: '<Seleccionar>', value: '' },
      { label: 'A', value: 'a' },
      { label: 'B', value: 'b' },
      { label: 'C', value: 'c' },
      { label: 'D', value: 'd' },
      { label: 'E', value: 'e' },
      { label: 'F', value: 'f' },
      { label: 'G', value: 'g' },
      { label: 'H', value: 'h' },
      { label: 'I', value: 'i' },
      { label: 'J', value: 'j' },
      { label: 'K', value: 'k' },
      { label: 'L', value: 'l' },
      { label: 'M', value: 'm' },
      { label: 'N', value: 'n' },
      { label: 'O', value: 'o' },
      { label: 'P', value: 'p' },
      { label: 'Q', value: 'q' },
      { label: 'R', value: 'r' },
      { label: 'S', value: 's' },
      { label: 'T', value: 't' },
      { label: 'U', value: 'u' },
      { label: 'V', value: 'v' },
      { label: 'W', value: 'w' },
      { label: 'X', value: 'x' },
      { label: 'Y', value: 'y' },
    ],
  },
  {
    type: 'select',
    id: 'genre',
    label: 'Género',
    default: '',
    options: [
      { label: '<Seleccionar>', value: '' },
      { label: 'Adaptación de Novela', value: 'Adaptación de Novela' },
      { label: 'Aventuras', value: 'Aventuras' },
      { label: 'Bondage', value: 'Bondage' },
      { label: 'Comedia', value: 'Comedia' },
      { label: 'Drama', value: 'Drama' },
      { label: 'Ecchi', value: 'Ecchi' },
      { label: 'Escolar', value: 'Escolar' },
      { label: 'Fantasía', value: 'Fantasía' },
      { label: 'Hardcore', value: 'Hardcore' },
      { label: 'Harem', value: 'Harem' },
      { label: 'Isekai', value: 'Isekai' },
      { label: 'MILF', value: 'MILF' },
      { label: 'Netorare', value: 'Netorare' },
      { label: 'Novela', value: 'Novela' },
      { label: 'Recuentos de la vida', value: 'Recuentos de la vida' },
      { label: 'Romance', value: 'Romance' },
      { label: 'Seinen', value: 'Seinen' },
      { label: 'Sistemas', value: 'Sistemas' },
    ],
  },
  {
    type: 'select',
    id: 'status',
    label: 'Status',
    default: '',
    options: [
      { label: '<Seleccionar>', value: '' },
      { label: 'Completed', value: 'Completed' },
      { label: 'En Libertad', value: 'En Libertad' },
    ],
  },
];
