export const GENRES = [
  'Accion',
  'Adulto',
  'Animación',
  'Apocaliptico',
  'Artes Marciales',
  'Aventura',
  'Bestias',
  'Boys Love',
  'Ciberpunk',
  'Ciencia Ficción',
  'Comedia',
  'Crimen',
  'Demonios',
  'Deporte',
  'Dragones',
  'Drama',
  'Ecchi',
  'Extranjero',
  'Familia',
  'Fantasia',
  'Fantasmas',
  'Género Bender',
  'Girls Love',
  'Gore',
  'Guerra',
  'Harem',
  'Historia',
  'Horror',
  'Isekai',
  'Magia',
  'Mazmorra',
  'Mecha',
  'Militar',
  'Misterio',
  'Musica',
  'Niños',
  'Oeste',
  'Parodia',
  'Policiaco',
  'Psicológico',
  'Realidad',
  'Realidad Virtual',
  'Recuentos de la vida',
  'Reencarnación',
  'Regresión',
  'Romance',
  'Samurái',
  'Sistemas',
  'Smut',
  'Supernatural',
  'Superpoderes',
  'Supervivencia',
  'Telenovela',
  'Thriller',
  'Tragedia',
  'Transmigración',
  'Vampiros',
  'Venganza',
  'Vida Escolar',
  'Video Juegos',
  'Villana',
];
